---
kind: pipeline
type: kubernetes
name: default

steps:
- name: flake8
  image: python
  commands:
  - pip install -r requirements.txt
  - flake8 --statistics
- name: pytest
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest -v --cov

trigger:
  branch:
  - main
  event:
  - push