---
kind: pipeline
type: kubernetes
name: default

steps:
- name: flake8
  image: python
  commands:
  - pip install -r requirements.txt
  - flake8 --statistics
- name: pytest
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest -v --cov
- name: bandit
  image: python
  commands:
  - pip install bandit
  - bandit -x "./test_*" -r .
- name: safety
  image: python
  commands:
  - pip install safety
  - safety check

trigger:
  ref:
  - refs/heads/main